### ISSUE TITLE
Empty instructions on deno

### ISSUE THREAD

**Issue by joshhamon** [J053Fabi0/Duplicated-files-cleaner-Incognito#11]
Troubleshooting attempted:
remove db/database.db
remove entire directory and redownload

Instructions are []

**Comment by lukemax47** [comment]
@joshhamon What is the status of your nodes on the Node Monitor?

**Comment by joshhamon** [comment]
node_data_0 is syncing, the rest of are a mix of sync, unstake, waiting, etc

**Comment by BriCo84** [comment]
@joshhamon  have you been using this without issue and then this issue presented itself all of a sudden?

Or have you not been able to get it working at any point yet?

**Comment by joshhamon** [comment]
It appears to be an issue with node_0 not being at latest before running deno. Closing comment
