### ISSUE TITLE
After updating deno I can not longer use this script

### ISSUE THREAD

**Issue by BriCo84** [J053Fabi0/Duplicated-files-cleaner-Incognito#12]
When trying to run the script, which has been working without issue for weeks now, I get this error after updating to the latest deno

Uncaught Error: Deno.core.evalContext is not supported in this environment

I did a fresh pull but that did not change anything.

**Comment by J053Fabi0** [comment]
You're right, it's happening to me too. I'll look into it

**Comment by J053Fabi0** [comment]
It's working now. Please do a git pull and retry.

**Comment by BriCo84** [comment]
Worked, thanks!
