### ISSUE TITLE
nodes going in to committee while script is running

### ISSUE THREAD

**Issue by BriCo84** [J053Fabi0/Duplicated-files-cleaner-Incognito#13]
I have noticed that the script can take some time to run, and based on the new epoch time of 1.5 hours, scheduling the crontab task is impossible to pick a time when epochs wont be possibly ending.  Right now the script checks committee assignment as either in committee, pending, syncing, etc.  But it doesn't check how many epochs left until committee.  So what is happening is....

Script checks for example and sees node 0 is pending, so it runs the script for node 0...as it is running the script for node 0, node 0 goes in to committee.  Typically this is not a problem as even if the script takes some time to run, it SHOULD be done before the window is up for the node to get back online and get over 50 vote threshold, however, sometimes the nodes don't always come back online.  And what I am seeing is, node 0 then goes in to committee while the script is being run.  The script finishes, and node 0 is not back online but is in committee.

There is a lot "checking" after the script is run to make sure the nodes are back online. 

My suggestion is, instead of just checking if a node is in committee and skipping it if it is, add a if/then branch for if a node is in 
"pending" check the number of epochs left till committee, if epochs left is less than 3, SKIP the node (sometimes node monitor lists as 2 epochs until committee but then goes straight in to committee from there, so need to check for 2 or less epochs to be safe).

It would in fact be even better if this variable could be adjusted in the script.  If it was up to me, i would set it to skip any node that will be in committee in 5 epochs or less.

This will drastically reduce the number of nodes that get slashed from this issue happening AND make it less vital to be checking the nodes in node monitor after crontab runs scheduled task (which for me is twice a day).

Just my humble suggestion, thanks

**Comment by J053Fabi0** [comment]
It's done. The default `maxEpochsToNextEvent` is 3. You can set it through the `constants.ts` file as shown in the examples. Thank you for the suggestion, it was not humble at all, but very clever.
