### ISSUE TITLE
getting errors on latest pull, won't run

### ISSUE THREAD

**Issue by BriCo84** [J053Fabi0/Duplicated-files-cleaner-Incognito#15]
I did a git pull after the changes you made the other day, now I am getting errors when trying to run.  It won't run succesfully.  After getting the instructions it outputs the following and then exits.

![temp](https://user-images.githubusercontent.com/4989699/219823541-dd61f1ad-065d-4cb7-a111-cdd01cf72c74.png)

**Comment by J053Fabi0** [comment]
please run `git pull && git checkout issue-15-testing`, re-run the script and show me the output, please.

**Comment by BriCo84** [comment]
![temp](https://user-images.githubusercontent.com/4989699/219824623-02b067e5-e756-4761-ae32-6d0f8cf305bb.png)

**Comment by J053Fabi0** [comment]
re-run the deno script and show me the output, please.

**Comment by BriCo84** [comment]
![temp](https://user-images.githubusercontent.com/4989699/219825965-b4928e12-052f-4268-a393-78a88fad21a5.png)

**Comment by J053Fabi0** [comment]
That's an error with the API, I don't know what's causing it, but it might be some sort of restriction set by them. I just added a flag to the script so you can skip those checks, just be sure that none of your nodes is in committee before running it: `deno task run --skip-checks`. Please do a git pull and tell me if it fixes the problem. The shown roles for your nodes should be `UNKNOWN` when running it with the flag.

**Comment by BriCo84** [comment]
It just started though when I tried running after you made the recent code changes.  Is it not related to that?

I really don't ever not have nodes in committee so I can't run it with the checks skipped.

**Comment by J053Fabi0** [comment]
It may be that because now I check for all the nodes at once the restriction emerges if you have too many nodes. How many do you have?

**Comment by BriCo84** [comment]
50

**Comment by J053Fabi0** [comment]
Maybe you have more. I'm getting the error at 51 nodes. Try it with the latest update, I made it so that it only fetches a maximum of 40 nodes at once in chunks.

**Comment by BriCo84** [comment]
Since doing this special branch you asked me to test, I can't seem to get back to the master branch.  When I try to do a git pull I get the below error

![image](https://user-images.githubusercontent.com/4989699/230141192-a0c4c57f-b106-4bc3-b0c5-9bce3ef7121b.png)

Please help me get back to the master branch
