### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by xtrbacon** [J053Fabi0/Duplicated-files-cleaner-Incognito#4]
Seeing the following error when I attempt to run.

duplicatedfilescleaner@1.0.0 start /home/xtrbacon/Duplicated-files-cleaner-Incognito
node index.js

Database loaded.
Getting instructions.
Instructions:
[ { shardName: 'shard0',
    fromNodeIndex: 3,
    toNodesIndex: [ 9, 8, 7, 6, 5, 4, 2 ] },
  { shardName: 'beacon',
    fromNodeIndex: 0,
    toNodesIndex: [ 10, 9, 8, 7, 6, 5, 4, 3, 2, 1 ] } ]

Getting roles.
  TypeError: Promise.allSettled is not a function
      at getNodesInfo (/home/xtrbacon/Duplicated-files-cleaner-Incognito/getNodesInfo.js:14:17)
      at /home/xtrbacon/Duplicated-files-cleaner-Incognito/index.js:17:25
      at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by J053Fabi0** [comment]
Please update node to the minimum required version, it's in the readme.md.

**Comment by xtrbacon** [comment]
Thanks,  I thought I had updated to latest level but it turned out I needed to log out and log back in.

Now I get to the point of making sure all files are editable and get a long list of permission errors.   I verified all files are owned by incognito.

Making sure all files are editable to the incognito user.
stderr: chown: changing ownership of '/home/incognito/node_data_6/173.37-2022-10-13.log': Operation not permitted
chown: changing ownership of '/home/incognito/node_data_6/23.132-2022-10-11.log'stderr: : Operation not permitted
chown: changing ownership of '/home/incognito/node_data_6/error.log': Operation not permitted
stderr: chown: changing ownership of '/home/incognito/node_data_6/mainnet/listenerpeer.json': Operation not permitted
stderr: chown: changing ownership of '/home/incognito/node_data_6/mainnet/block/shard3/000002.ldb': Operation not permitted
chown: changing ownership of '/home/incognito/node_data_6/mainnet/block/shard3/LOCK': Operation not permitted
chown: changing ownership of '/home/incognito/node_data_6/mainnet/block/shard3/CURRENT.bak': Operation not permitted
stderr: chown: changing ownership of '/home/incognito/node_data_6/mainnet/block/shard3/000029.log': Operation not permitted
chown: changing ownership of '/home/incognito/node_data_6/mainnet/block/shard3/MANIFEST-000030': Operation not permitted
chown: changing ownership of '/home/incognito/node_data_6/mainnet/block/shard3/CURRENT': Operation not permitted
chown: changing ownership of '/home/incognito/node_data_6/mainnet/block/shard3/LOG': Operation not permitted
chown: changing ownership of '/home/incognito/node_data_6/mainnet/block/shard3': Operation not permitted
stderr: chown: changing ownership of '/home/incognito/node_data_6/mainnet/block/shard7/000002.ldb': Operation not permitted

**Comment by J053Fabi0** [comment]
Try running the command yourself with sudo: 

```bash
sudo chown incognito:incognito -R /home/incognito
```

**Comment by xtrbacon** [comment]
yes, that is what I did prior to my last update when I mentioned that I verify all files are owned by incognito.  Just tried it again and still get same operation not permitted error

**Comment by J053Fabi0** [comment]
Then I'm not sure what's happening. You could try to run the script as sudo.

**Comment by taruneldho** [comment]
I'm getting the same issue as well
