### ISSUE TITLE
Empty instructions

### ISSUE THREAD

**Issue by taruneldho** [J053Fabi0/Duplicated-files-cleaner-Incognito#5]
> duplicatedfilescleaner@1.0.0 start
> node index.js

Database loaded.
Getting instructions.
Instructions:
[]

Getting roles.
  ┌─────────┬───────────┐
  │ (index) │  Values   │
  ├─────────┼───────────┤
  │    0    │ 'SYNCING' │
  │    1    │ 'SYNCING' │
  │    2    │ 'SYNCING' │
  └─────────┴───────────┘

Stopping containers.
  inc_mainnet_0
  inc_mainnet_1
  inc_mainnet_2

Making sure all files are editable to the incognito user.

Starting containers.
  inc_mainnet_0
  inc_mainnet_1
  inc_mainnet_2

Done!

**Comment by J053Fabi0** [comment]
Are you running the script with node or deno?

**Comment by taruneldho** [comment]
Node

**Comment by J053Fabi0** [comment]
Can I see your constants file?

**Comment by taruneldho** [comment]
```
ubuntu@vps-044a5d20:~/Projects/Duplicated-files-cleaner-Incognito$ cat constants.js
module.exports = {
  homePath: "/home/incognito",

  // The key is the index they occupy as a docker container.
  // The value is the validator public key.

  // These are examples.
  validatorPublicKeys: {
    0: "16ycS5YXnvnVEW9mVJJvQdQWid596m9L2W3iBcQdLvGVdQ4LpczvLPK6VavNNXHCZnxE5NpvKxDyc8Sgp8k3UbdWXHhYSVYBDaZHYmncbMaxegPFM8ozoc2mkWsdBbFxhNjdhajcTqAEbABofzSwRuSwhDP1mRJWEh5uLc8GniE7H6iFCtmLv",
    1: "1NqzY89Fnw4VJDNmgqp5cAC8jMaRB7NxcZ6k4Q9GpiTt2zURMRufpc5f55CoH3r8i7aNP59vLtKsYTQioFqXmX7HntftUyADYPXYEcL4ZetjAFjNggWAc91N4uzUYnfrsDc7FiRrEnmjZt2LG3FFzjzdpxKvHVwmdvftCj1Ay3B6g3DdzqGfn",
    2: "1Wf2igyKXFmk1t8Q8BgCdYqLDjYuRXg3YyrSKm4EF1vTW8yWcXBmuwjNbfJfSotapaJeEXWiG1DyZ2CB1ZVQvkjQWdFEEyct9VvsyxG2aKZySCoCzhkd6thjuTQ5WkiUVbg81V6ENFJY6oZW3U9ZaSiWYKsoTNYc4dJKTAo4M3YtS9RYuKFzN",
  },
};
```

**Comment by J053Fabi0** [comment]
Is the issue solved?

**Comment by taruneldho** [comment]
Instructions are coming in with the latest but failing on permissions.

**Comment by J053Fabi0** [comment]
Run it with sudo

**Comment by taruneldho** [comment]
Running it with sudo makes no difference either

**Comment by J053Fabi0** [comment]
which is the error?

**Comment by taruneldho** [comment]
Permission denied on `rm` command

**Comment by J053Fabi0** [comment]
can you copy and past the exact output of the entire script? not just the error
