### ISSUE TITLE
Errors out when encountering the new blockstorage folder

### ISSUE THREAD

**Issue by joshhamon** [J053Fabi0/Duplicated-files-cleaner-Incognito#6]
The latest update from Incognito has added a ```blockstorage``` folder in the shard and beacon folders. The new origin and the deno branches error out when encountering the folder.

**Comment by J053Fabi0** [comment]
I see. I haven't got the new update. Can you please help me by telling me the new this address would have now `/home/incognito/node_data_1/mainnet/block/shard0`.

**Comment by J053Fabi0** [comment]
Oh, never mind, I see the update.

**Comment by J053Fabi0** [comment]
Solved by the latest commit.

https://github.com/J053Fabi0/Duplicated-files-cleaner-Incognito/commit/ceb6910d4c102c96c4c570cc307b55b387ed4b38
