### ISSUE TITLE
Deno - error removing directory during processing

### ISSUE THREAD

**Issue by xtrbacon** [J053Fabi0/Duplicated-files-cleaner-Incognito#7]
shard0
    Prossesing node 10
    Error: rm: cannot remove '/home/incognito/node_data_10/mainnet/block/shard0/blockstorage': Is a directory
        at spawnPromise (file:///home/xxxxxx/incognito/Duplicated-files-cleaner-Incognito/utils/spawnPromise.ts:28:32)
        at async file:///home/xxxxxx/incognito/Duplicated-files-cleaner-Incognito/index.ts:65:9

**Comment by J053Fabi0** [comment]
Run a git pull and try again. Tell me if it works then.

**Comment by xtrbacon** [comment]
Works now, Thanks!
