### ISSUE TITLE
I have to reinstall deno every time I want to use it

### ISSUE THREAD

**Issue by joshhamon** [J053Fabi0/Duplicated-files-cleaner-Incognito#8]
Each time I go to use the new script, I have to install deno again. Is there something I'm missing?

**Comment by xtrbacon** [comment]
@joshhamon 

Do you have to re-install?  Or just run the export DENO_INSTALL and export PATH?   If it is the later try adding the exports to .bashrc,  that worked for me.

**Comment by joshhamon** [comment]
I tried looking up how to export to .bashrc but didn't find it quickly

**Comment by xtrbacon** [comment]
nano ~/.bashrc

add the two export commands
